accel_Kp: 0.025
#0.08能良好适应1m/s^2的首次目标，之后调整震荡较低
#0.05能良好适应3m/s^s的首次目标，之后调整震荡较低
accel_Ki: 0.0
accel_Kd: 0.0 #Kp/200

#disable speed control, so dosen't matter
min_accel: 0.001

# override the default values of the pid speed controller
# (only relevant for ackermann control mode)
speed_Kp: 0.05
speed_Ki: 0.00
speed_Kd: 0.50


# 向前降低油门的时候：
#实际的throttle<target_pedal，导致target_pedal 立刻上升，从而throttle跟着target_pdel一起上升
#升高后，反而离目标accel更远，所以又下降。需要拉客target_pedal和throttle的平行距离（避免过快交叉）
